version: '3'

services:
  db:
    build: ./database
    container_name: ipt_local_db
    ports:
      - 3306:3306
    expose:
      - '3306'

  web:
    build: 
      context: ./server
    env_file:
      - ./web.env
    container_name: flask_server
    ports:
      - 6000:6000
    expose:
      - '6000'

  ngrok:
    image: wernight/ngrok:latest
    container_name: ngrok_server
    environment:
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_PORT: 0.0.0.0:6000
    ports:
      - 4040:4040
    
